port: 7890
socks-port: 7891
mixed-port: 7893
redir-port: 7892
bind-address: '*'
mode: rule
allow-lan: true
log-level: warning
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
unified-delay: true
ipv6: true
secret : 
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  nameserver:
    - https://cloudflare-dns.com/dns-query
  fallback:
    - https://dns.google/dns-query  
proxies:
  - {name: maretmaster, server: idtj-tifa.bonds.id, port: 443, udp: true, type: trojan, password: 832c11a0-a0f3-11ec-9085-1239d0255272, sni: v24.tiktokcdn.com, skip-cert-verify: true}
proxy-groups:
- name: MARETMASTER
  type: url-test
  tolerance: 99
  use:
  - maretmaster
rules:
  - MATCH,AKUN 
